# Generated by Django 5.2 on 2025-10-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
